### PR TITLE
Add TAG_Long_Array support, bump to 1.5B

### PR DESCRIPTION
**Pull request by peerkoel**
Adding support for TAG_Long_Array. Suggested bump to 1.5 Beta with new JAR file.

### CODE REVIEW

**Comment by justisr** [comment]
This PR is missing the actual LongArrayTag class. Source won’t compile. Suggesting a new PR @peerkoel

**Comment by peerkoel** [comment]
> This PR is missing the actual LongArrayTag class. Source won’t compile. Suggesting a new PR @peerkoel

Excellent suggestion, see https://github.com/Morlok8k/JNBT/pull/10

**Comment by peerkoel** [comment]
Hi,

Hopefully I have reached Morlok8k. I would like to remind you that for 
quite a few years there has been an approved pull request on the JNBT 
code that I submitted. Could you go and merge it?
If there is any need to contact me, use ***@***.***
-- 
Kind regards,
Peter Koeleman

**Comment by Morlok8k** [comment]
yeah, i already pulled this one. assume you meant #10 which i just pulled in.

**Comment by justisr** [comment]
This PR doesn’t correctly implement Long array support in the NBTOutputsteam. See https://github.com/Morlok8k/JNBT/blob/823179fe06792c55cae05f18cca0bb773ceb7a18/src/org/jnbt/NBTOutputStream.java#L358

writeLong should be changed to writeInt on this line. This int represents the length of the array in bytes. It is an int regardless of the datatype used. As it stands, this will corrupt any output that needs to write a long array.

Cheers

**Comment by Morlok8k** [comment]
Please submit a PR then

**Pull request merged**
